// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_gforce = NULL;
lv_obj_t * ui_bgGauge = NULL;
lv_obj_t * ui_dot = NULL;
lv_obj_t * ui_Accel = NULL;
lv_obj_t * ui_Brake = NULL;
lv_obj_t * ui_Left = NULL;
lv_obj_t * ui_Right = NULL;
// event funtions

// build funtions

void ui_gforce_screen_init(void)
{
    ui_gforce = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_gforce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgGauge = lv_img_create(ui_gforce);
    lv_img_set_src(ui_bgGauge, &ui_img_gforcegauge_asset_1_png);
    lv_obj_set_width(ui_bgGauge, LV_SIZE_CONTENT);   /// 520
    lv_obj_set_height(ui_bgGauge, LV_SIZE_CONTENT);    /// 520
    lv_obj_set_align(ui_bgGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgGauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot = lv_img_create(ui_gforce);
    lv_img_set_src(ui_dot, &ui_img_dot_asset_2_png);
    lv_obj_set_width(ui_dot, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_dot, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_align(ui_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Accel = lv_label_create(ui_gforce);
    lv_obj_set_width(ui_Accel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accel, 0);
    lv_obj_set_y(ui_Accel, 200);
    lv_obj_set_align(ui_Accel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accel, "0.00");
    lv_obj_set_style_text_color(ui_Accel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Accel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Accel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brake = lv_label_create(ui_gforce);
    lv_obj_set_width(ui_Brake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Brake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Brake, 0);
    lv_obj_set_y(ui_Brake, -200);
    lv_obj_set_align(ui_Brake, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brake, "0.00");
    lv_obj_set_style_text_color(ui_Brake, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Brake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Brake, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left = lv_label_create(ui_gforce);
    lv_obj_set_width(ui_Left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left, 200);
    lv_obj_set_y(ui_Left, 0);
    lv_obj_set_align(ui_Left, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Left, "0.00");
    lv_obj_set_style_text_color(ui_Left, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Left, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Right = lv_label_create(ui_gforce);
    lv_obj_set_width(ui_Right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Right, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Right, -200);
    lv_obj_set_y(ui_Right, 0);
    lv_obj_set_align(ui_Right, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Right, "0.00");
    lv_obj_set_style_text_color(ui_Right, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Right, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_gforce_screen_destroy(void)
{
    if(ui_gforce) lv_obj_del(ui_gforce);

    // NULL screen variables
    ui_gforce = NULL;
    ui_bgGauge = NULL;
    ui_dot = NULL;
    ui_Accel = NULL;
    ui_Brake = NULL;
    ui_Left = NULL;
    ui_Right = NULL;

}
