// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_GFORCE_H
#define UI_GFORCE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_gforce
extern void ui_gforce_screen_init(void);
extern void ui_gforce_screen_destroy(void);
extern lv_obj_t * ui_gforce;
extern lv_obj_t * ui_bgGauge;
extern lv_obj_t * ui_dot;
extern lv_obj_t * ui_Accel;
extern lv_obj_t * ui_Brake;
extern lv_obj_t * ui_Left;
extern lv_obj_t * ui_Right;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

